export const QUESTION_BANK = [
  // FÁCIL (Verdadeiro ou Falso) - 20 Perguntas
  { id: 1, type: 'true_false', difficulty: 'Fácil', text: "Frans Krajcberg usava troncos de árvores queimadas para denunciar o desmatamento.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 2, type: 'true_false', difficulty: 'Fácil', text: "'Ice Watch', de Olafur Eliasson, usou blocos de gelo para alertar sobre o aquecimento global.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 3, type: 'true_false', difficulty: 'Fácil', text: "Uma 'obra efêmera' é aquela feita para durar para sempre em um museu.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  { id: 4, type: 'true_false', difficulty: 'Fácil', text: "Cildo Meireles usou garrafas de refrigerante para circular ideias durante a ditadura.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 5, type: 'true_false', difficulty: 'Fácil', text: "As arpilleras chilenas eram esculturas de metal feitas por operários.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  { id: 6, type: 'true_false', difficulty: 'Fácil', text: "O 'Homem lixo', de HA Schult, foi feito com peças eletrônicas descartadas.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 7, type: 'true_false', difficulty: 'Fácil', text: "Arte pública é aquela exibida exclusivamente em galerias particulares e fechadas.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  { id: 8, type: 'true_false', difficulty: 'Fácil', text: "O Projeto Tamar usa a música no Movimento Tamarear para defender as tartarugas marinhas.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 9, type: 'true_false', difficulty: 'Fácil', text: "Consumo sustentável envolve comprar apenas o que é necessário e evitar desperdícios.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 10, type: 'true_false', difficulty: 'Fácil', text: "Instalações sonoras integram artes visuais e música com interação do público.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 11, type: 'true_false', difficulty: 'Fácil', text: "O artista HA Schult afirma que vivemos na 'Era da Reciclagem'.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  { id: 12, type: 'true_false', difficulty: 'Fácil', text: "As mulheres chilenas usavam sacos de batata e farinha para criar as arpilleras.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 13, type: 'true_false', difficulty: 'Fácil', text: "A obra 'Homem Cabelo' de HA Schult utiliza embalagens de cosméticos e bobes de cabelo.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 14, type: 'true_false', difficulty: 'Fácil', text: "Cildo Meireles imprimia mensagens apenas em dinheiro, nunca em garrafas.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  { id: 15, type: 'true_false', difficulty: 'Fácil', text: "Jaime Prades usa garrafas PET para fazer suas instalações de barcos.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 16, type: 'true_false', difficulty: 'Fácil', text: "O artista Ai Weiwei fez uma obra com cercas para falar sobre a situação dos refugiados.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 17, type: 'true_false', difficulty: 'Fácil', text: "O grupo 'Ciclo Natural' compra instrumentos caros em lojas de música.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  { id: 18, type: 'true_false', difficulty: 'Fácil', text: "O artista Tunga criou a obra 'True Rouge' usando redes e madeira.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 19, type: 'true_false', difficulty: 'Fácil', text: "As arpilleras chegaram à Europa e foram chamadas pelo governo chileno de 'tapeçarias da difamação'.", options: ["Verdadeiro", "Falso"], correct: "Verdadeiro" },
  { id: 20, type: 'true_false', difficulty: 'Fácil', text: "O sítio Natura, onde Krajcberg vivia, fica no estado de São Paulo.", options: ["Verdadeiro", "Falso"], correct: "Falso" },
  // MÉDIO (Múltipla Escolha) - 20 Perguntas
  { id: 21, type: 'multiple_choice', difficulty: 'Médio', text: "O artista polonês naturalizado brasileiro, famoso por esculturas com restos de árvores queimadas é:", options: ["Cildo Meireles", "Frans Krajcberg", "Olafur Eliasson", "Ai Weiwei"], correct: "Frans Krajcberg" },
  { id: 22, type: 'multiple_choice', difficulty: 'Médio', text: "A técnica têxtil usada por mulheres chilenas para denunciar a ditadura e o sumiço de familiares chama-se:", options: ["Arpillera", "Macramê", "Grafite", "Mosaico"], correct: "Arpillera" },
  { id: 23, type: 'multiple_choice', difficulty: 'Médio', text: "Qual artista criou as 'Inserções em circuitos ideológicos' imprimindo mensagens em cédulas de dinheiro?", options: ["HA Schult", "Jaime Prades", "Cildo Meireles", "Ernesto Neto"], correct: "Cildo Meireles" },
  { id: 24, type: 'multiple_choice', difficulty: 'Médio', text: "O projeto 'Ice Watch' (Relógio de gelo) alerta principalmente sobre qual problema ambiental?", options: ["Desmatamento", "Aquecimento global", "Lixo eletrônico", "Poluição dos rios"], correct: "Aquecimento global" },
  { id: 25, type: 'multiple_choice', difficulty: 'Médio', text: "Como o artista HA Schult descreve o momento atual, refletido em obras como o 'Homem lixo'?", options: ["Era do Gelo", "Era da Tecnologia", "Era do Lixo", "Era Sustentável"], correct: "Era do Lixo" },
  { id: 26, type: 'multiple_choice', difficulty: 'Médio', text: "O que caracteriza uma obra de 'arte pública'?", options: ["Estar em ruas e praças", "Pertencer a coleções", "Ser feita de ouro", "Ser vendida cara"], correct: "Estar em ruas e praças" },
  { id: 27, type: 'multiple_choice', difficulty: 'Médio', text: "O grupo 'Ciclo Natural', do Rio de Janeiro, constrói instrumentos musicais a partir de:", options: ["Madeira nobre", "Sucata descartada", "Ouro e prata", "Cristal de vidro"], correct: "Sucata descartada" },
  { id: 28, type: 'multiple_choice', difficulty: 'Médio', text: "O que é consumo consciente?", options: ["Comprar sempre o novo", "Consumir sem desperdício", "Trocar celular todo ano", "Acumular embalagens"], correct: "Consumir sem desperdício" },
  { id: 29, type: 'multiple_choice', difficulty: 'Médio', text: "O artista Jaime Prades usa garrafas PET na instalação 'À deriva' para simbolizar:", options: ["Céu estrelado", "Poluição das águas", "Animais em extinção", "Cidades"], correct: "Poluição das águas" },
  { id: 30, type: 'multiple_choice', difficulty: 'Médio', text: "Artesãs de Poconé (MT) adaptaram a técnica da arpillera para retratar a flora e fauna de qual região?", options: ["Amazônia", "Caatinga", "Pantanal", "Pampas"], correct: "Pantanal" },
  { id: 31, type: 'multiple_choice', difficulty: 'Médio', text: "Onde o artista Olafur Eliasson expôs os blocos de gelo da obra 'Ice Watch'?", options: ["Nova York", "Londres", "Tóquio", "Rio de Janeiro"], correct: "Londres" },
  { id: 32, type: 'multiple_choice', difficulty: 'Médio', text: "A obra 'Êxodo', do artista Ai Weiwei, tem foco em qual problema global?", options: ["Desmatamento", "Crise dos Refugiados", "Aquecimento global", "Uso de Plásticos"], correct: "Crise dos Refugiados" },
  { id: 33, type: 'multiple_choice', difficulty: 'Médio', text: "A artista norte-americana Ann P. Smith reutiliza qual tipo de material para compor suas esculturas de robôs?", options: ["Garrafas PET", "Papelão", "Eletrodomésticos/Eletrônicos", "Tecidos velhos"], correct: "Eletrodomésticos/Eletrônicos" },
  { id: 34, type: 'multiple_choice', difficulty: 'Médio', text: "A instalação 'True Rouge', de Tunga, fica em qual famoso instituto em Minas Gerais?", options: ["MASP", "Inhotim", "Pinacoteca", "MAM"], correct: "Inhotim" },
  { id: 35, type: 'multiple_choice', difficulty: 'Médio', text: "O Movimento 'Tamarear' conta com a participação de qual famoso cantor brasileiro (segundo a imagem)?", options: ["Caetano Veloso", "Gilberto Gil", "Milton Nascimento", "Roberto Carlos"], correct: "Milton Nascimento" },
  { id: 36, type: 'multiple_choice', difficulty: 'Médio', text: "Qual foi a principal estratégia das arpilleristas durante a ditadura chilena?", options: ["Resistência armada", "Resistência não violenta", "Fuga para o Brasil", "Ocultar o passado"], correct: "Resistência não violenta" },
  { id: 37, type: 'multiple_choice', difficulty: 'Médio', text: "O sítio 'Natura', casa e ateliê de Frans Krajcberg, ficava no sul de qual estado?", options: ["Rio de Janeiro", "Bahia", "Paraná", "Ceará"], correct: "Bahia" },
  { id: 38, type: 'multiple_choice', difficulty: 'Médio', text: "O que o grupo 'Ciclo Natural' também cria, além de instrumentos, para envolver as artes visuais e a música?", options: ["Pinturas a óleo", "Instalações sonoras", "Estátuas de mármore", "Roupas de moda"], correct: "Instalações sonoras" },
  { id: 39, type: 'multiple_choice', difficulty: 'Médio', text: "A obra 'Boas cercas fazem bons vizinhos' (Ai Weiwei) foi inspirada em um poema de:", options: ["Robert Frost", "William Shakespeare", "Fernando Pessoa", "Carlos Drummond"], correct: "Robert Frost" },
  { id: 40, type: 'multiple_choice', difficulty: 'Médio', text: "A palavra 'Tamar', do Projeto Tamar, vem da junção de quais duas palavras?", options: ["Tartaruga + Marinha", "Tempo + Amar", "Tatu + Martelo", "Terra + Mar"], correct: "Tartaruga + Marinha" },
  // DIFÍCIL (Digitação - 1 Palavra) - 20 Perguntas
  { id: 41, type: 'text_input', difficulty: 'Difícil', text: "Qual é o país de origem das bordadeiras que criaram a técnica 'arpilleras'?", correct: "Chile" },
  { id: 42, type: 'text_input', difficulty: 'Difícil', text: "Que material da natureza derretia nas ruas na obra 'Ice Watch'?", correct: "Gelo" },
  { id: 43, type: 'text_input', difficulty: 'Difícil', text: "Qual animal é protegido pelo Projeto Tamar e inspirou um Movimento Musical?", correct: "Tartaruga" },
  { id: 44, type: 'text_input', difficulty: 'Difícil', text: "Em qual embalagem Cildo Meireles inseria mensagens contra a censura?", correct: "Garrafa" },
  { id: 45, type: 'text_input', difficulty: 'Difícil', text: "Que tipo de lixo (adjetivo) compõe a escultura 'Homem Lixo' de HA Schult?", correct: "Eletronico" },
  { id: 46, type: 'text_input', difficulty: 'Difícil', text: "Obras expostas em ruas e praças são classificadas como Arte...", correct: "Publica" },
  { id: 47, type: 'text_input', difficulty: 'Difícil', text: "Obras feitas para desaparecerem com o tempo são chamadas de obras...", correct: "Efêmeras" },
  { id: 48, type: 'text_input', difficulty: 'Difícil', text: "Cildo Meireles usou cédulas de qual objeto para espalhar suas 'inserções'?", correct: "Dinheiro" },
  { id: 49, type: 'text_input', difficulty: 'Difícil', text: "Frans Krajcberg usava restos de árvores atingidas por qual desastre ambiental?", correct: "Queimada" },
  { id: 50, type: 'text_input', difficulty: 'Difícil', text: "A técnica têxtil do Chile, feita em sacos de farinha, chama-se...", correct: "Arpillera" },
  { id: 51, type: 'text_input', difficulty: 'Difícil', text: "Qual artista alemão criou esculturas humanas feitas inteiramente de lixo (Sobrenome)?", correct: "Schult" },
  { id: 52, type: 'text_input', difficulty: 'Difícil', text: "Em qual estado brasileiro as artesãs de Poconé fazem a 'arpilharia' pantaneira?", correct: "Mato Grosso" },
  { id: 53, type: 'text_input', difficulty: 'Difícil', text: "De qual região do mundo vieram os grandes blocos de gelo do 'Ice Watch'?", correct: "Groenlandia" },
  { id: 54, type: 'text_input', difficulty: 'Difícil', text: "Em qual famosa cidade inglesa a obra 'Ice Watch' foi montada nas ruas?", correct: "Londres" },
  { id: 55, type: 'text_input', difficulty: 'Difícil', text: "Na obra 'À deriva', de Jaime Prades, milhares de garrafas PET representam a água de qual local geográfico (plural)?", correct: "Rios" },
  { id: 56, type: 'text_input', difficulty: 'Difícil', text: "A obra 'Homem Cabelo' usa embalagens de qual tipo de produto (ex: shampoo, creme)?", correct: "Cosmeticos" },
  { id: 57, type: 'text_input', difficulty: 'Difícil', text: "Qual o primeiro nome do artista chinês famoso pela obra dos refugiados ('Boas cercas...')?", correct: "Ai" },
  { id: 58, type: 'text_input', difficulty: 'Difícil', text: "O grupo 'Ciclo Natural' une a música às artes...", correct: "Visuais" },
  { id: 59, type: 'text_input', difficulty: 'Difícil', text: "O Projeto Tamar foi criado em 1980 e cuida da preservação da fauna...", correct: "Marinha" },
  { id: 60, type: 'text_input', difficulty: 'Difícil', text: "O conjunto de esculturas de Krajcberg em Nova Viçosa usa troncos queimados de árvores do...", correct: "Mangue" },
];